#!/usr/bin/env bash
#==============================================================================
# clean-gaming-cache--nvidia.sh
#
# DESCRIPTION:
#   Cleans all gaming-related cache directories used by Wine, DXVK, Mesa,
#   NVIDIA GLCache, Vulkan pipeline cache, and Winetricks.
#
#   The script removes ONLY cache files and temporary data. It does NOT touch
#   Wine prefixes, configuration files, installed applications, or user data.
#
#   Uses centralized logging via logger.sh and color definitions from colors.
#
# CLEANED DIRECTORIES:
#
#   ~/.cache/dxvk_state
#       DXVK pipeline state cache (.dxvk-cache). Stores precompiled pipeline
#       states to reduce stutter during shader compilation.
#
#   ~/.cache/dxvk_shader
#       NVIDIA __GL_SHADER_DISK_CACHE for DXVK. Stores compiled GLSL shaders
#       generated by the Vulkan driver.
#
#   ~/.cache/mesa_shader_cache
#       Mesa shader cache for RADV/ANV. Stores compiled SPIR-V → ISA shaders.
#
#   ~/.cache/mesa
#       Additional Mesa driver cache (pipeline metadata, shader variants).
#
#   ~/.cache/nv, ~/.cache/nvidia, ~/.nv/GLCache
#       NVIDIA OpenGL/Vulkan shader cache. Stores compiled binary shaders and
#       pipeline objects for faster startup and reduced stutter.
#
#   ~/.cache/wine
#       Wine shader cache and internal temporary files created by wined3d,
#       vkd3d, and other Wine subsystems.
#
#   ~/.cache/winetricks
#       Cached installers and metadata downloaded by winetricks.
#
#   ~/.cache/vulkan, ~/.cache/amdvlk
#       Vulkan pipeline cache used by the Vulkan loader and GPU drivers.
#
#   $WINEPREFIX/drive_c/users/*/AppData/Local/Temp
#       Windows-style Temp directory inside the Wine prefix. Safe to clear;
#       contains leftover installer files, logs, and temporary runtime data.
#
#   *.dxvk-cache inside the Wine prefix
#       Per-application DXVK pipeline caches stored directly in the prefix.
#
# USAGE:
#   ./clean-gaming-cache--nvidia.sh
#
# REQUIREMENTS:
#   - logger.sh and colors must be located in the same directory as this script.
#   - Wine installed and WINEPREFIX set inside the script.
#
# AUTHOR:
#   dawciobiel (http://github.com/dawciobiel)
#
# CREATED:
#   2025-12-24
#==============================================================================


SCRIPT_DIR="$(dirname "$0")"

# Load logger + colors
if [ -f "$SCRIPT_DIR/logger.sh" ]; then
    source "$SCRIPT_DIR/logger.sh"
else
    echo "logger.sh not found!"
    exit 1
fi

# Optional: enable debug logs
DEBUG_MODE=0

# Log file (optional)
LOG_FILE="$SCRIPT_DIR/clean-gaming-cache.log"

# Wine prefix
WINEPREFIX="/home/dawciobiel/Games/wine-sc2"

log_header "Cleaning gaming-related cache"

# -----------------------------
# DXVK (global)
# -----------------------------
log_info "Cleaning DXVK (global)..."
rm -rf ~/.cache/dxvk_state/* 2>/dev/null
rm -rf ~/.cache/dxvk_shader/* 2>/dev/null
log_success "DXVK global cache cleaned"

# -----------------------------
# Mesa shader cache
# -----------------------------
log_info "Cleaning Mesa shader cache..."
rm -rf ~/.cache/mesa_shader_cache/* 2>/dev/null
rm -rf ~/.cache/mesa/* 2>/dev/null
log_success "Mesa shader cache cleaned"

# -----------------------------
# NVIDIA shader cache
# -----------------------------
log_info "Cleaning NVIDIA GLCache..."
rm -rf ~/.cache/nv/* 2>/dev/null
rm -rf ~/.cache/nvidia/* 2>/dev/null
rm -rf ~/.nv/GLCache/* 2>/dev/null
log_success "NVIDIA GLCache cleaned"

# -----------------------------
# Wine cache
# -----------------------------
log_info "Cleaning Wine cache..."
rm -rf ~/.cache/wine/* 2>/dev/null
log_success "Wine cache cleaned"

# -----------------------------
# Winetricks cache
# -----------------------------
log_info "Cleaning Winetricks cache..."
rm -rf ~/.cache/winetricks/* 2>/dev/null
log_success "Winetricks cache cleaned"

# -----------------------------
# Vulkan pipeline cache
# -----------------------------
log_info "Cleaning Vulkan pipeline cache..."
rm -rf ~/.cache/vulkan/* 2>/dev/null
rm -rf ~/.cache/amdvlk/* 2>/dev/null
log_success "Vulkan pipeline cache cleaned"

# -----------------------------
# Temp inside Wine prefix
# -----------------------------
log_info "Cleaning Temp inside Wine prefix..."
rm -rf "$WINEPREFIX/drive_c/users/"*/AppData/Local/Temp/* 2>/dev/null
log_success "Wine prefix Temp cleaned"

# -----------------------------
# DXVK cache inside prefix
# -----------------------------
log_info "Cleaning DXVK cache inside Wine prefix..."
find "$WINEPREFIX" -type f -name "*.dxvk-cache" -delete 2>/dev/null
log_success "DXVK prefix cache cleaned"

# -----------------------------
# Done
# -----------------------------
log_header "Cache cleanup completed"
log_success "Gaming environment is clean and ready"

