# DXVK variables
#
# Pokazuje HUD z FPS i informacjami DXVK w rogu ekranu.
DXVK_HUD=0 \
#
# For NVIDIA cards:
__GL_SHADER_DISK_CACHE=1 \
# __GL_SHADER_DISK_CACHE=1 – włącza buforowanie skompilowanych shaderów na dysku, co przyspiesza kolejne uruchomienia gier.
__GL_SHADER_DISK_CACHE_PATH="$WINEPREFIX/shader_cache" \
# __GL_SHADER_DISK_CACHE_PATH="$WINEPREFIX/shader_cache" – określa, gdzie ma być zapisywana pamięć podręczna shaderów.
#
# For AMD cards:
# RADV_PERFTEST=aco \
#
# DXVK_ASYNC=0 – wyłącza asynchroniczną kompilację shaderów w DXVK.
#  Gdy DXVK_ASYNC=0 (wyłączone – domyślnie): gra czeka na skompilowanie shaderów przed ich użyciem, co może powodować mikroprzycięcia (stuttering), ale jest bardziej "bezpieczne" pod kątem zgodności.
#  Gdy DXVK_ASYNC=1 (włączone): shadery są kompilowane w tle, gra może działać płynniej, ale może naruszać zasady np. w grach online (anticheat).
#  Uwaga:
#   Asynchroniczna kompilacja wymaga własnoręcznej kompilacji DXVK z odpowiednią łatką (tzw. async patch), bo nie jest oficjalnie wspierana.
#   Jeśli nie masz tej wersji, DXVK_ASYNC=1 nie będzie miało żadnego efektu.
DXVK_ASYNC=1 \
#
#
# Logging
# Jeżeli nie ma błędów przy wyświetlaniu grafiki to ze względu na wydajność lepiej logi w ogóle wyłączyć.
#  none	Wyłącza całkowicie logi DXVK.
#  error	Pokazuje tylko poważne błędy.
#  warn	Pokazuje ostrzeżenia i błędy (domyślny).
#  info	Pokazuje dodatkowe informacje — np. używane rozszerzenia Vulkan.
#  debug	Bardzo szczegółowe logi — do zaawansowanego debugowania.
DXVK_LOG_LEVEL=none \
#
# Disable DXVK and enable only DirectX 9 or 11
# WINEDLLOVERRIDES="dxgi,d3d11=n" \
