# UWAGA! Jeżeli jakaś zmienna jest ustawiana, to może jej składowa część nie może być zmieniana w kolejnych liniach!

# DXVK
# https://github.com/doitsujin/dxvk

### Notes on Vulkan drivers
# Before reporting an issue, please check the [Wiki](https://github.com/doitsujin/dxvk/wiki/Driver-support) page on the current driver status and make sure you run a recent enough driver version for your hardware.

### HUD
# The DXVK_HUD environment variable controls a HUD which can display the framerate and some stat counters. It accepts a comma-separated list of the following options:
#
# devinfo: Displays the name of the GPU and the driver version.
# fps: Shows the current frame rate.
# frametimes: Shows a frame time graph.
# submissions: Shows the number of command buffers submitted per frame.
# drawcalls: Shows the number of draw calls and render passes per frame.
# pipelines: Shows the total number of graphics and compute pipelines.
# descriptors: Shows the number of descriptor pools and descriptor sets.
# memory: Shows the amount of device memory allocated and used.
# allocations: Shows detailed memory chunk suballocation info.
# gpuload: Shows estimated GPU load. May be inaccurate.
# version: Shows DXVK version.
# api: Shows the D3D feature level used by the application.
# cs: Shows worker thread statistics.
# compiler: Shows shader compiler activity
# samplers: Shows the current number of sampler pairs used [D3D9 Only]
# ffshaders: Shows the current number of shaders generated from fixed function state [D3D9 Only]
# swvp: Shows whether or not the device is running in software vertex processing mode [D3D9 Only]
# scale=x: Scales the HUD by a factor of x (e.g. 1.5)
# opacity=y: Adjusts the HUD opacity by a factor of y (e.g. 0.5, 1.0 being fully opaque).
#
# Additionally, DXVK_HUD=1 has the same effect as DXVK_HUD=devinfo,fps, and DXVK_HUD=full enables all available HUD elements.

# UWAGA! Jeżeli jakaś zmienna jest ustawiana, to może jej składowa część nie może być zmieniana w kolejnych liniach!
# dxvk.hud=fps,gpuload,opacity=1.0,scale=1.8
dxvk.hud=fps,opacity=1.0,scale=1.8
