# Mangohud variables
# https://github.com/flightlessmango/MangoHud?tab=readme-ov-file#hud-configuration

MANGOHUD=0
MANGOHUD_CONFIG=cpu_temp,gpu_temp,cpu_stats,fps,offset_x=1,offset_y=3

#offset_x offset_y	HUD position offsets



# UWAGA: Niektóre zmienne (np. output_file) działają tylko w wybranych wersjach MangoHUD
# Sprawdź: mangohud --help lub dokumentację wersji zbudowanej lokalnie
# Logi domyślnie zapisywane są w ~/.local/share/MangoHUD

# MANGOHUD_OUTPUT_FILE=/home/dawciobiel/Games/battlenet-logs
output_file=/home/dawciobiel/Games/battlenet-logs
MANGOHUD_OUTPUT=0
MANGOHUD_LOG_PER_MINUTE=0
MANHOUND_LOG_LEVEL=none
