# Debug mode
DEBUG_MODE=0

# Logger
LOG_DIR="$HOME/Games/battlenet-logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/battlenet-$(date +'%Y%m%d-%H%M%S').log"

# Config for Wine
WINEARCH=win64
WINE_HOME="/usr"
# WINEPREFIX to folder "podsystemu Windows" - czyli całego tego WinAPI
WINEPREFIX="$HOME/Games/wine-10.8_staging"

# WINEDEBUG=-fixme,+err \
# WINEDEBUG=+err,+warn \
# WINDEBUG=-all,+err,-fixme, \
# WINEDEBUG=-all,+err,+warn \
# WINEDEBUG=+err,+warn,+d3d,+d3d11,+d3d9,+vulkan \
WINEDEBUG="-all"

# Battlenet Installer
BATTLENET_INSTALLER="Battle.net-Setup.exe"

# Battlenet Launcher desktop link
BATTLENET_DESKTOP_LINK="$HOME/.local/share/applications/starcraft2.desktop"

# Battlenet Launcher .exe file
BATTLENET_EXE="drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe"

# StarCraft 2 game .exe file
# Ścieżka "/mnt/<mount_name_path>/StarCraft II/Support64/SC2Switcher_x64.exe" jest widoczna zarównoa dla systemu linux jak i dla Battlenet Launcher'a uruchomionego pod WINE.
# Dlatego grę z poziomu Battlenet Launcher warto instalować w scieżce /mnt
SC2_EXE="/mnt/WD1200/part1/games/StarCraft II/Support64/SC2Switcher_x64.exe"

# Battlenet Launcher home directory
# FIXME lepiej byłoby trzymać katalog INSTALL_DIR (czyli pliki gier) poza katalogiem WINEPREFIX, żeby nie były uzależnione od jego reinstalacji, ale w praktyce Battle.net instaluje je wewnątrz
INSTALL_DIR="$WINEPREFIX"

