# ===============================================
#  Debug Mode
# ===============================================

# Tryb debugowania – jeśli ustawione na 1, włącza 'set -x' (czyli śledzenie wykonywania poleceń Bash)
# 0 — tryb normalny (bez debugowania)
# 1 — tryb debugowania (diagnostyka, dodatkowe logi)
# If set to 1, enables Bash debug output (equivalent to running the script with 'set -x').
DEBUG_MODE=1


# ===============================================
#  Logger
# ===============================================

# Katalog logów Battle.net / StarCraft II
LOG_DIR="$HOME/Games/battlenet-logs"

# Tworzy katalog logów (jeśli nie istnieje)
mkdir -p "$LOG_DIR"

# Plik logu z aktualnego uruchomienia
LOG_FILE="$LOG_DIR/battlenet-$(date +'%Y%m%d-%H%M%S').log"

# ===============================================
#  Config for Gamemode
# ===============================================
USE_GAMEMODE=0


# ===============================================
#  Config for Wine
# ===============================================

# WINEARCH działa tylko przy tworzeniu prefixu – decyduje, czy Wine zbuduje go jako win32, win64 albo experimental WoW64.
# Dopuszczalne są tylko wartości:  win32, win64
WINEARCH="win64"

# Lokalizacja katalogu instalacyjnego Wine (np. /usr lub /opt/wine-staging)
WINE_HOME="/usr"
WINE_BIN="/bin/wine"
WINE_SERVER_BIN="/bin/wineserver"

# WINEPREFIX — folder „podsystemu Windows” (czyli środowisko WinAPI)
WINEPREFIX="/home/dawciobiel/Games/wine-sc2"

# WINEDEBUG — poziom szczegółowości logów Wine
# WINEDEBUG=[+/-]channel
# Dostępne przykłady:
#   WINEDEBUG=-all
#   WINEDEBUG=-fixme,+err \
#   WINEDEBUG=+err,+warn \
#   WINEDEBUG=-all,+err,-fixme, \
#   WINEDEBUG=-all,+err,+warn \
#   WINEDEBUG=+err,+warn,+d3d,+d3d11,+d3d9,+vulkan \
#
# Zalecane ustawienie dla normalnego uruchamiania (bez spamu w logach):
# WINEDEBUG="-all" \
# Wersja alternatywna (więcej informacji diagnostycznych):
WINEDEBUG="-all" \
# WINEDEBUG="+d3d,+dxgi,+d3d11,+seh,+loaddll"


# ===============================================
#  Battle.net
# ===============================================

# Instalator Battle.net (plik .exe)
BATTLENET_INSTALLER="Battle.net-Setup.exe"

# Ścieżka do skrótu .desktop uruchamiającego Battle.net
BATTLENET_DESKTOP_LINK="$HOME/.local/share/applications/starcraft2.desktop"

# Główne .exe launchera Battle.net (uruchamiane przez Wine)
BATTLENET_EXE="drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe"


# ===============================================
#  StarCraft II
# ===============================================

# Ścieżka do pliku wykonywalnego gry StarCraft II
# Uwaga:
#   Ścieżka "/mnt/<mount_name_path>/StarCraft II/Support64/SC2Switcher_x64.exe"
#   jest widoczna zarówno dla Linuxa, jak i dla Battle.net uruchomionego pod Wine.
#   Dlatego grę z poziomu Battle.net warto instalować w ścieżce /mnt.

# To remove this variable from the code, and wine.conf. Because this variable is named wrong.
SC2_EXE="/mnt/WD120EFBX-68B0EN0/c3b190ae-e13a-4861-8166-a9c231243f1d/dawciobiel/Games/Starcraft.2.linux/StarCraft II/Support64/SC2Switcher_x64.exe"

# Proper named variable for 'SC2Switcher_x64.exe' file.
SC2SWITCHER_X64_EXE="/mnt/WD120EFBX-68B0EN0/c3b190ae-e13a-4861-8166-a9c231243f1d/dawciobiel/Games/Starcraft.2.linux/StarCraft II/Support64/SC2Switcher_x64.exe"

# Proper name for 'SC2_x64.exe' file.
SC2_x64_EXE="/mnt/WD120EFBX-68B0EN0/c3b190ae-e13a-4861-8166-a9c231243f1d/dawciobiel/Games/Starcraft.2.linux/StarCraft II/Versions/Base95299/SC2_x64.exe"

# ===============================================
#  Installation Directory
# ===============================================

# Domyślny katalog instalacyjny Battle.net
# FIXME:
#   Lepiej byłoby trzymać katalog INSTALL_DIR (czyli pliki gry) poza katalogiem WINEPREFIX — dzięki temu nie one zależne
#   od jego reinstalacji. W praktyce jednak Battle.net Launcher instaluje gre wewnątrz katalogu prefixu.
INSTALL_DIR="$WINEPREFIX"
